ROOT := $(shell git rev-parse --show-toplevel)
DIST := $(ROOT)/dist
PY   := uv run python3
# The evaluation harness is the one build step that is not stdlib-only: it reports
# capability-boundary overhead and sandbox-tier results, both of which need
# wasmtime (the `poc` group). `uv run --group poc` installs it on demand, so this
# needs no separate setup step in CI.
PY_POC := uv run --group poc python3

# ── Shared research artifact ─────────────────────────────────────────
# graphs/*.json and diagrams/*.typ live at the repository root and back
# every *living* paper. Their rendered figures land in dist/graphs and
# dist/diagrams; living papers reference them root-absolutely (/dist/...).
GRAPHS_SRC := $(filter-out graphs/schema.json,$(wildcard graphs/*.json))
GRAPHS_TXT := $(patsubst graphs/%.json,$(DIST)/graphs/%.graph,$(GRAPHS_SRC))
GRAPHS_SVG := $(patsubst graphs/%.json,$(DIST)/graphs/%.svg,$(GRAPHS_SRC))

DIAGRAMS_SRC := $(wildcard diagrams/*.typ)
DIAGRAMS_SVG := $(patsubst diagrams/%.typ,$(DIST)/diagrams/%.svg,$(DIAGRAMS_SRC))

# ── Paper corpus ─────────────────────────────────────────────────────
# Documents live under papers/<id>/; outputs under dist/papers/<id>/.
#
# Paper 1 (frozen) is self-contained: it carries its own pinned graph
# JSONs and diagram source and builds *only* from them, so it can never
# drift as the shared artifact evolves. Its frozen proposal.typ references
# figures with relative `dist/...` paths (it is byte-identical to the
# freeze commit and must not be edited); the committed symlink
# papers/01-vision/dist -> ../../dist/papers/01-vision makes those paths
# resolve to its own output tree, for both typst (file-relative) and
# pandoc (cwd-relative).
P1_DIR := papers/01-vision
P1_OUT := $(DIST)/papers/01-vision
P1_GRAPHS_SRC := $(filter-out $(P1_DIR)/graphs/schema.json,$(wildcard $(P1_DIR)/graphs/*.json))
P1_GRAPH_TXT  := $(patsubst $(P1_DIR)/graphs/%.json,$(P1_OUT)/graphs/%.graph,$(P1_GRAPHS_SRC))
P1_GRAPH_SVG  := $(patsubst $(P1_DIR)/graphs/%.json,$(P1_OUT)/graphs/%.svg,$(P1_GRAPHS_SRC))
P1_DIAG_SVG   := $(patsubst $(P1_DIR)/diagrams/%.typ,$(P1_OUT)/diagrams/%.svg,$(wildcard $(P1_DIR)/diagrams/*.typ))
P1_DOCS := $(P1_OUT)/proposal.pdf $(P1_OUT)/proposal.md $(P1_OUT)/proposal.html

# Publication-named PDF alias. Convention: each paper's PDF is also emitted as
# a citable, self-identifying copy named lavi-<year>-<slug>.pdf — the file to
# upload to venues. Internal build names stay proposal.*. The year is finalised
# at publication (Paper 1: 2026, Zenodo, doi:10.5281/zenodo.21473361; Paper 2:
# provisional until published — rename if the year slips).
P1_PUB_PDF := $(P1_OUT)/lavi-2026-architecture-as-program.pdf

# Paper 2 (living) builds from the shared top-level artifact.
P2_DIR := papers/02-demonstrator
P2_OUT := $(DIST)/papers/02-demonstrator
P2_DOCS := $(P2_OUT)/proposal.pdf $(P2_OUT)/proposal.md $(P2_OUT)/proposal.html
P2_PUB_PDF := $(P2_OUT)/lavi-2026-confinement-by-construction.pdf

# Paper 3 (living) is the method/accounting paper. It interpolates no
# evaluation data — every figure it refers to is cited to Paper 2 — so it
# depends on citations.bib alone, not on the graph or evaluation artifacts.
P3_DIR := papers/03-method
P3_OUT := $(DIST)/papers/03-method
P3_DOCS := $(P3_OUT)/proposal.pdf $(P3_OUT)/proposal.md $(P3_OUT)/proposal.html
P3_PUB_PDF := $(P3_OUT)/lavi-2026-predicting-before-building.pdf

# Inspector figures: committed screenshots regenerated by the UI's e2e run
# (`make ui-e2e`), copied into dist/ for Paper 2 the same way the committed
# WASM artifacts serve the tests — the corpus build itself never needs Node.
#
# Which screenshots Paper 2 actually uses is *derived from the paper source*
# rather than listed here, on the same single-source principle as the graph
# figures: the paper references one of the five, and hardcoding that filename
# would either ship four unused images or silently break the HTML the day a
# second figure is added. Only the referenced ones are staged and copied.
UI_FIGS_USED := $(sort $(shell grep -oh '/dist/ui/[A-Za-z0-9_-]*\.png' $(P2_DIR)/proposal.typ | sed 's|/dist/ui/||'))
UI_FIGS := $(addprefix $(DIST)/ui/,$(UI_FIGS_USED))

# Deprecated compatibility aliases: dist/proposal.{pdf,md,html} are copies of
# Paper 2's outputs, kept for one transition so existing inbound links and the
# GitHub Pages deploy keep working. Remove once those links point at
# dist/papers/02-demonstrator/ (see README).
ALIASES := $(DIST)/proposal.pdf $(DIST)/proposal.md $(DIST)/proposal.html

.PHONY: build clean validate-graphs test wasm check-freeze grammar evaluation paper1 paper2 paper3 aliases api ui ui-check ui-e2e

build: validate-graphs check-freeze grammar evaluation paper1 paper2 paper3 aliases
	@echo "Build complete."

grammar: $(DIST)/grammar.md
evaluation: $(DIST)/evaluation.md $(DIST)/evaluation.json
paper1: $(P1_DOCS) $(P1_PUB_PDF)
paper2: $(P2_DOCS) $(P2_PUB_PDF)
paper3: $(P3_DOCS) $(P3_PUB_PDF)
aliases: $(ALIASES)

# Grammar card — built from scripts/type_parser.py and the canonical
# graph JSONs so that the documented grammar and subtype rules cannot
# drift from the implementation without failing the build.
$(DIST)/grammar.md: scripts/emit-grammar.py scripts/type_parser.py $(GRAPHS_SRC) | $(DIST)
	$(PY) scripts/emit-grammar.py

# Evaluation artifact — the demonstrator's own evidence, run and consolidated:
# the graph-mutation corpus (each case pinned to an expected verdict *and* the
# reason class it must be caught by), the capability-boundary overhead against
# the stated envelope, and the prompt-injection outcome on both tiers. Emits both
# evaluation.md (for a reader) and evaluation.json (what Paper 2 typesets from).
# Generated like the grammar card so the paper's Evaluation section cannot drift
# from the code: a divergence from a pin fails the build rather than quietly
# rewriting the table.
POC_SRC  := $(wildcard poc/*.py) $(wildcard poc/sandbox/*.py)
POC_WASM := $(wildcard poc/sandbox/wasm/*.wasm)
$(DIST)/evaluation.md: $(POC_SRC) $(POC_WASM) $(GRAPHS_SRC) scripts/graph_validator.py scripts/type_parser.py | $(DIST)
	$(PY_POC) -m poc.evaluate

# One run, two serialisations: evaluation.md for a reader, evaluation.json for
# Paper 2's Evaluation section, which loads it with typst's `json()` so its
# tables are typeset from the run rather than transcribed from it. Both come out
# of the single recipe above (this make is 3.81 — no grouped `&:` targets), so
# this rule only has to establish the ordering and assert the file appeared.
$(DIST)/evaluation.json: $(DIST)/evaluation.md
	@test -f $@ || { echo "poc.evaluate did not write $@" >&2; exit 1; }

# Validate the shared graph JSON files: structural, type-aware, cross-graph.
# Depends on `test` so validator-logic changes are tested before use.
# (Paper 1's pinned graphs are frozen historical inputs, guarded by check-freeze
# rather than re-validated against the current schema.)
validate-graphs: test $(GRAPHS_SRC) scripts/validate-graphs.py scripts/graph_validator.py scripts/type_parser.py graphs/schema.json
	@$(PY) scripts/validate-graphs.py

# Guard the frozen paper against silent edits: its sources must match the
# freeze commit. Skips (with a warning) if the commit is unavailable, e.g. a
# shallow CI checkout.
check-freeze:
	@$(PY) scripts/check-freeze.py

# Run the test suite (type parser + graph validator + runtime) via pytest.
test:
	@uv run pytest

# ── Shared figure generation (backs living papers) ──────────────────
# Generate pseudocode and diagram source from canonical graph JSON.
$(DIST)/graphs/%.graph $(DIST)/graphs/%.typ: graphs/%.json scripts/generate-graph.py | $(DIST)/graphs
	$(PY) scripts/generate-graph.py $<

# Compile diagram Typst to SVG.
$(DIST)/graphs/%.svg: $(DIST)/graphs/%.typ
	typst compile $< $@ --format svg --root $(ROOT)

# Hand-written illustrative diagrams.
$(DIST)/diagrams/%.svg: diagrams/%.typ | $(DIST)/diagrams
	typst compile $< $@ --format svg --root $(ROOT)

# ── Paper 1 (frozen): figures from its own pinned inputs ────────────
$(P1_OUT)/graphs/%.graph $(P1_OUT)/graphs/%.typ: $(P1_DIR)/graphs/%.json scripts/generate-graph.py | $(P1_OUT)/graphs
	$(PY) scripts/generate-graph.py $< $(P1_OUT)/graphs

$(P1_OUT)/graphs/%.svg: $(P1_OUT)/graphs/%.typ
	typst compile $< $@ --format svg --root $(ROOT)

$(P1_OUT)/diagrams/%.svg: $(P1_DIR)/diagrams/%.typ | $(P1_OUT)/diagrams
	typst compile $< $@ --format svg --root $(ROOT)

# Paper 1 documents. typst reads figures through the papers/01-vision/dist
# symlink; --root keeps that (real) path inside the project root.
$(P1_OUT)/proposal.pdf: $(P1_DIR)/proposal.typ citations.bib $(P1_GRAPH_TXT) $(P1_GRAPH_SVG) $(P1_DIAG_SVG) | $(P1_OUT)
	typst compile $(P1_DIR)/proposal.typ $@ --root $(ROOT) --pdf-standard a-2b

$(P1_PUB_PDF): $(P1_OUT)/proposal.pdf
	cp $< $@

# pandoc for Paper 1 runs from the paper directory so its relative `dist/...`
# figure paths resolve through the symlink; project files are reached via ../../.
$(P1_OUT)/proposal.md: $(P1_DIR)/proposal.typ citations.bib $(P1_GRAPH_TXT) $(P1_GRAPH_SVG) $(P1_DIAG_SVG) scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/clean-markdown.py | $(P1_OUT)
	cd $(P1_DIR) && pandoc proposal.typ -f typst -t markdown --wrap=none \
		--lua-filter=$(ROOT)/scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=$(ROOT)/citations.bib --csl=$(ROOT)/scripts/ieee.csl \
		-o $@
	$(PY) scripts/clean-markdown.py $@

$(P1_OUT)/proposal.html: $(P1_DIR)/proposal.typ citations.bib $(P1_GRAPH_TXT) $(P1_GRAPH_SVG) $(P1_DIAG_SVG) scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/proposal.css scripts/clean-html.py | $(P1_OUT)
	cd $(P1_DIR) && pandoc proposal.typ -f typst -t html --standalone --wrap=none \
		--lua-filter=$(ROOT)/scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=$(ROOT)/citations.bib --csl=$(ROOT)/scripts/ieee.csl \
		--css=proposal.css \
		-o $@
	$(PY) scripts/clean-html.py $@
	cp scripts/proposal.css $(P1_OUT)/

# ── Paper 2 (living): figures from the shared artifact ──────────────
$(DIST)/ui/%.png: ui/screenshots/%.png | $(DIST)/ui
	cp $< $@

$(P2_OUT)/proposal.pdf: $(P2_DIR)/proposal.typ citations.bib $(GRAPHS_TXT) $(GRAPHS_SVG) $(DIAGRAMS_SVG) $(DIST)/evaluation.json $(UI_FIGS) | $(P2_OUT)
	typst compile $(P2_DIR)/proposal.typ $@ --root $(ROOT) --pdf-standard a-2b

$(P2_PUB_PDF): $(P2_OUT)/proposal.pdf
	cp $< $@

$(P2_OUT)/proposal.md: $(P2_DIR)/proposal.typ citations.bib $(GRAPHS_TXT) $(GRAPHS_SVG) $(DIAGRAMS_SVG) $(DIST)/evaluation.json $(UI_FIGS) scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/clean-markdown.py | $(P2_OUT)
	pandoc $(P2_DIR)/proposal.typ -f typst -t markdown --wrap=none \
		--lua-filter=scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=citations.bib --csl=scripts/ieee.csl \
		-o $@
	$(PY) scripts/clean-markdown.py $@

# HTML output is self-contained in its own dir: copy in the referenced SVGs and
# the stylesheet so the page renders standalone (clean-html.py rewrites figure
# paths to bare graphs/… and diagrams/… relative to the HTML).
$(P2_OUT)/proposal.html: $(P2_DIR)/proposal.typ citations.bib $(GRAPHS_TXT) $(GRAPHS_SVG) $(DIAGRAMS_SVG) $(DIST)/evaluation.json $(UI_FIGS) scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/proposal.css scripts/clean-html.py | $(P2_OUT)
	pandoc $(P2_DIR)/proposal.typ -f typst -t html --standalone --wrap=none \
		--lua-filter=scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=citations.bib --csl=scripts/ieee.csl \
		--css=proposal.css \
		-o $@
	$(PY) scripts/clean-html.py $@
	cp scripts/proposal.css $(P2_OUT)/
	@mkdir -p $(P2_OUT)/graphs $(P2_OUT)/diagrams $(P2_OUT)/ui
	cp $(GRAPHS_SVG) $(P2_OUT)/graphs/
	cp $(DIAGRAMS_SVG) $(P2_OUT)/diagrams/
	cp $(UI_FIGS) $(P2_OUT)/ui/

# Paper 3 documents. No figures, no interpolated data: the method paper cites
# Paper 2 for every measurement, so citations.bib is its only input beyond the
# source. Kept deliberately: a second document able to state a number is a
# second document able to disagree.
$(P3_OUT)/proposal.pdf: $(P3_DIR)/proposal.typ citations.bib | $(P3_OUT)
	typst compile $(P3_DIR)/proposal.typ $@ --root $(ROOT) --pdf-standard a-2b

$(P3_PUB_PDF): $(P3_OUT)/proposal.pdf
	cp $< $@

$(P3_OUT)/proposal.md: $(P3_DIR)/proposal.typ citations.bib scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/clean-markdown.py | $(P3_OUT)
	pandoc $(P3_DIR)/proposal.typ -f typst -t markdown --wrap=none \
		--lua-filter=scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=citations.bib --csl=scripts/ieee.csl \
		-o $@
	$(PY) scripts/clean-markdown.py $@

$(P3_OUT)/proposal.html: $(P3_DIR)/proposal.typ citations.bib scripts/resolve-crossrefs.lua scripts/ieee.csl scripts/proposal.css scripts/clean-html.py | $(P3_OUT)
	pandoc $(P3_DIR)/proposal.typ -f typst -t html --standalone --wrap=none \
		--lua-filter=scripts/resolve-crossrefs.lua \
		--citeproc --bibliography=citations.bib --csl=scripts/ieee.csl \
		--css=proposal.css \
		-o $@
	$(PY) scripts/clean-html.py $@
	cp scripts/proposal.css $(P3_OUT)/

# ── Deprecated aliases → Paper 2 (transition only) ──────────────────
$(DIST)/proposal.pdf: $(P2_OUT)/proposal.pdf | $(DIST)
	cp $< $@

$(DIST)/proposal.md: $(P2_OUT)/proposal.md | $(DIST)
	cp $< $@

# The alias HTML lives directly in dist/, where its bare graphs/… and diagrams/…
# figure references resolve against the shared dist/graphs and dist/diagrams.
$(DIST)/proposal.html: $(P2_OUT)/proposal.html scripts/proposal.css | $(DIST)
	cp $(P2_OUT)/proposal.html $@
	cp scripts/proposal.css $(DIST)/

# ── Graph inspector (opt-in; never part of `make build`) ────────────
# The UI's toolchain (Node) is isolated in ui/ with its own lockfile; the
# corpus build must succeed on a machine with no Node at all (the committed
# ui/screenshots/*.png serve the paper figures, regenerated by `make ui-e2e`).

# The Python execution API on its own (http://127.0.0.1:8123).
api:
	$(PY_POC) -m poc.inspector_api

# API + Next.js dev server together; Ctrl-C stops both.
ui:
	cd ui && npm install
	@trap 'kill 0' EXIT INT TERM; \
	$(PY_POC) -m poc.inspector_api & \
	cd ui && npm run dev

# Typecheck + production build of the UI.
ui-check:
	cd ui && npm install && npm run typecheck && npm run build

# End-to-end checks of the paper-facing claims; regenerates ui/screenshots/.
ui-e2e:
	cd ui && npm install && npm run e2e

# ── WASM sandbox tier (unchanged) ───────────────────────────────────
RUST_DIR    := $(ROOT)/poc/sandbox/rust
WASM_OUT    := $(ROOT)/poc/sandbox/wasm
# NOT wasm32-wasip1/wasip2: those link std against WASI, so the artifact would
# import fd_write/environ_get (wasip1) or wasi:cli/* (wasip2) even when it never
# uses them. Building for unknown-unknown and converting to a component with no
# WASI adapter leaves an import set containing only the node's capability
# interfaces — which is the property the component tier exists to demonstrate.
WASM_TARGET := wasm32-unknown-unknown
WASM_MODULES := node_parse_message node_moderate_content node_fetch_context \
                node_generate_response node_send_reply hostile_ambient hostile_ungranted

# Build the component-tier WASM node artifacts and copy them into
# poc/sandbox/wasm/ (which is committed).
#
# Two steps, and the second is the interesting one:
#   1. cargo builds each node crate to a *core* module. wit_bindgen::generate!
#      reads poc/sandbox/wit/caps.wit and emits the typed bindings, plus a
#      `component-type` custom section describing the crate's world.
#   2. `wasm-tools component new` reads that section and wraps the core module
#      into a *component* whose imports and exports are the WIT interfaces. No
#      `--adapt` flag is passed: no WASI adapter is linked, so the component
#      imports nothing but its declared capability interfaces.
#
# Requires a Rust toolchain with the wasm32-unknown-unknown target
# (`rustup target add wasm32-unknown-unknown`) and wasm-tools
# (`brew install wasm-tools` / `cargo install wasm-tools`). This is NOT part of
# `make build` or the pre-commit hooks — the committed artifacts let the sandbox
# tests run without either toolchain. Rebuild only when the Rust sources or the
# WIT change.
wasm:
	cargo build --manifest-path $(RUST_DIR)/Cargo.toml --release --target $(WASM_TARGET)
	@mkdir -p $(WASM_OUT)
	@for m in $(WASM_MODULES); do \
		wasm-tools component new \
			$(RUST_DIR)/target/$(WASM_TARGET)/release/$$m.wasm \
			-o $(WASM_OUT)/$$m.wasm ; \
		echo "  wrote poc/sandbox/wasm/$$m.wasm (component)" ; \
	done

# ── Output directories ──────────────────────────────────────────────
$(DIST) $(DIST)/graphs $(DIST)/diagrams $(DIST)/ui $(P1_OUT) $(P1_OUT)/graphs $(P1_OUT)/diagrams $(P2_OUT) $(P3_OUT):
	mkdir -p $@

clean:
	rm -rf $(DIST)
